In [1]:
import sys
from pathlib import Path
# Production layout: add project root and src for imports (run from repo root or notebooks/ingestion/)
_root = Path(".").resolve()
if _root.name == "ingestion":
    _root = _root.parent.parent
elif (_root / "src").is_dir():
    pass
else:
    _root = _root.parent
sys.path.insert(0, str(_root))
sys.path.insert(0, str(_root / "src"))

from storage.postgres.pgConn import PgConn
from storage.postgres import PostgresSQL_table_queries
from storage.cloud.CloudStorage import CloudStorageProvider

import pandas as pd
from datetime import datetime

In [2]:
table_name = PostgresSQL_table_queries.FINANCIAL_NEWS_TABLE_NAME
pg_conn = PgConn(table_name)
df = pg_conn.get_financial_news()
if df is None:
    raise RuntimeError(
        "get_financial_news() failed — check the error printed above "
        "(connection, table name, or schema)."
    )

Connection to the database successful!
Table name set to: financial_news_241118

In [3]:
print(f"Total news articles queried: {df.shape[0]}")

Total news articles queried: 10080

In [4]:
df.head()

,id,source,headline,href,summary,content,author,minsread,datetime
0,45876047236640910017045281208231353781,Motley Fool,"""Tokenized"" Stocks Are Breaking Down Barriers....",https://finance.yahoo.com/news/tokenized-stock...,,In This Article:\nHOOD\n+0.23%\nAAPL\n-0.12%\n...,"Alex Carchidi, The Motley Fool",6 min read,2025-07-23T17:19:00.000Z
1,220799662638683730910896676542146227596,CoinDesk,"""We're a Tweet Away from a 15% Dump:"" CEO on C...",https://finance.yahoo.com/video/were-tweet-awa...,,"In today's Markets Outlook, CoinDesk's Jennife...",CoinDesk,,2025-10-31T17:34:16.000Z
2,47514014236007877639078711690178672970,Motley Fool,$1 Billion in New Capital Could Soon Flow to X...,https://finance.yahoo.com/news/1-billion-capit...,,In this article:\nXRP-USD\n-0.06%\nKey Points\...,"Alex Carchidi, The Motley Fool",5 min read,2025-11-02T11:35:00.000Z
3,152599983586513563130066357372522406611,Coinspeaker,"$1.2B Left BTC ETFs This Week, but Not All is ...",https://finance.yahoo.com/news/1-2b-left-btc-e...,,In this article:\nBTC-USD\n+0.22%\nSOSO-USD\n+...,Parth Dubey,2 min read,2025-10-18T10:15:49.000Z
4,214287918542718613358470608080600126044,TheStreet,$1.5M Bitcoin prediction firm Ark Invest calls...,https://finance.yahoo.com/news/1-5m-bitcoin-pr...,According to ARK Invest's latest Bitcoin month...,"The Cathie Wood-owned firm believes Bitcoin, w...",Anushka Basu,2 min read,2025-03-12T16:42:53.000Z

In [5]:
def delete_records_for_current_date(df, pg_conn):
    if df is None:
        print("DataFrame is empty. No records to delete.")
        return
        
    # Filter DataFrame for records with today's date
    today = datetime.today().date()
    dt = pd.to_datetime(df['datetime'], errors='coerce')
    today_records = df[dt.dt.date == today]

    # Extract date strings (DB/delete API expects original string form)
    date_strings = today_records['datetime'].astype(str).tolist()

    # Call the delete_records_by_date method
    pg_conn.delete_records_by_date(date_strings)

# Then call the delete_records_for_current_date method
#delete_records_for_current_date(df, pg_conn)
#list_ids = ["11111"]
#pg_conn.delete_records_by_ids(list_ids)

In [6]:
class DataETL():
    
    def __init__(self, dataframe):
            self.df = dataframe
            self.cloudProvider = CloudStorageProvider()
            
    class Export():
        def __init__(self, dataframe):
            self.df = dataframe
            self.cloudProvider = CloudStorageProvider()
            
        def set_dataframe(self, dataframe):
            self.df = dataframe
        
        def export_text_to_s3(self, bucket_name, prefix_path, file_format):
            # Initialize AWS storage
            aws_storage = self.cloudProvider.AWS()

            # Create a new bucket
            aws_storage.create_bucket(bucket_name)

            # Upload DataFrame with datetime subfolder structure
            aws_storage.upload_dataframe_with_datetime_subfolders(self.df, bucket_name, prefix_path, file_format)
        
        def export_text_to_s3_full_file(self, bucket_name, prefix_path, filename):
            aws_storage = self.cloudProvider.AWS()
            aws_storage.upload_dataframe_to_csv(self.df, bucket_name, filename, prefix_path)
            
    class Ingestion():
        def __init__(self, dataframe):
            self.df = dataframe
            self.cloudProvider = CloudStorageProvider()
            
        def get_full_data_csv_file(self, bucket_name, prefix_path):
            # Initialize AWS storage
            aws_storage = self.cloudProvider.AWS()
            return aws_storage.get_csv_from_specific_folder(bucket_name, prefix_path)
        
        def get_data_csv_file_by_datetime(self, bucket_name, prefix_path, year, month, day, hour, minute):
            # Initialize AWS storage
            aws_storage = self.cloudProvider.AWS()
            return aws_storage.get_dataframe_from_specific_datetime(bucket_name, prefix_path, year=None, month=None, day=None, hour=None, minute=None)
    
    class Process():
        
        def __init__(self, dataframe):
            self.df = dataframe
        
        def getData():
            self.df = pg_conn.get_financial_news()
        
        def filter_by_current_date(self):
            today = datetime.today().date()
            dt = pd.to_datetime(self.df['datetime'], errors='coerce')
            return self.df[dt.dt.date == today]
            
    class Transform():
        def extractStopWords():
            pass

In [7]:
etl = DataETL(df)
etl_process = etl.Process(etl.df)
filtered_df = etl_process.filter_by_current_date()
filtered_df.head()

,id,source,headline,href,summary,content,author,minsread,datetime
71,112271484810819069292170596627025453439,decrypt,'Private Bitcoin' to Launch on Starknet With Z...,https://finance.yahoo.com/news/private-bitcoin...,,In this article:\nSTRK22691-USD\n-4.10%\nBTC-U...,André Beganski,3 min read,2026-02-26T23:01:12.000Z
93,79567273327088534030282011458120978368,Motley Fool,"1 Cryptocurrency to Consider Buying With $2,00...",https://finance.yahoo.com/news/1-cryptocurrenc...,,In this article:\nDOGE-USD\n-4.23%\nNVDA\n-5.4...,"Alex Carchidi, The Motley Fool",4 min read,2026-02-26T05:50:00.000Z
748,29911906174093391575825846216891467593,TheStreet,Another crypto executive accused of insider tr...,https://finance.yahoo.com/news/another-crypto-...,,In this article:\nBTC-USD\n-1.30%\nPopular onc...,Anand Sinha,3 min read,2026-02-26T17:23:15.000Z
941,316878550224202608217373602922154345297,24/7 Wall St.,BITI Shorts Bitcoin And Popped 25%. Now the Tr...,https://finance.yahoo.com/news/biti-shorts-bit...,,In this article:\nBTC-USD\n-1.41%\nQuick Read\...,Michael Williams,3 min read,2026-02-26T18:31:22.000Z
1204,312205210779296090874806522702446593963,Reuters,Binance cannot arbitrate customer claims over ...,https://finance.yahoo.com/news/binance-cannot-...,,"NEW YORK, Feb 26 (Reuters) - A federal judge o...",Reuters,1 min read,2026-02-26T23:39:45.000Z

In [8]:
print(f"Total filtered news articles queried: {filtered_df.shape[0]}")

Total filtered news articles queried: 49

In [9]:
export_rows_to_s3 = True
etl_export = etl.Export(filtered_df)
bucket_name = "test-financial-news-bucket"
prefix_path = "news/crypto"
file_format = "csv"
if export_rows_to_s3 == True and not filtered_df.empty:
    etl_export.export_text_to_s3(bucket_name, prefix_path, file_format)

Bucket 'test-financial-news-bucket' created successfully.
Data for row 71 with id '112271484810819069292170596627025453439' uploaded to S3 bucket 'test-financial-news-bucket' under folder 'news/crypto/year=2026/month=02/day=26/hour=23/minute=01/second=12/format=csv/112271484810819069292170596627025453439.csv'
Data for row 93 with id '79567273327088534030282011458120978368' uploaded to S3 bucket 'test-financial-news-bucket' under folder 'news/crypto/year=2026/month=02/day=26/hour=05/minute=50/second=00/format=csv/79567273327088534030282011458120978368.csv'
Data for row 748 with id '29911906174093391575825846216891467593' uploaded to S3 bucket 'test-financial-news-bucket' under folder 'news/crypto/year=2026/month=02/day=26/hour=17/minute=23/second=15/format=csv/29911906174093391575825846216891467593.csv'
Data for row 941 with id '316878550224202608217373602922154345297' uploaded to S3 bucket 'test-financial-news-bucket' under folder 'news/crypto/year=2026/month=02/day=26/hour=18/minute=31/second=22/format=csv/316878550224202608217373602922154345297.csv'
Data for row 1204 with id '312205210779296090874806522702446593963' uploaded to S3 bucket 'test-financial-news-bucket' under folder 'news/crypto/year=2026/month=02/day=26/hour=23/minute=39/second=45/format=csv/312205210779296090874806522702446593963.csv'
Data for row 1392 with id '123876605080908374676870972269491529023' uploaded to S3 bucket 'test-financial-news-bucket' under folder 'news/crypto/year=2026/month=02/day=26/hour=13/minute=17/second=15/format=csv/123876605080908374676870972269491529023.csv'
Data for row 1602 with id '328981430552959378496249003421795634619' uploaded to S3 bucket 'test-financial-news-bucket' under folder 'news/crypto/year=2026/month=02/day=26/hour=16/minute=55/second=27/format=csv/328981430552959378496249003421795634619.csv'
Data for row 1615 with id '241202333553108863868724904588471509590' uploaded to S3 bucket 'test-financial-news-bucket' under folder 'news/crypto/year=2026/month=02/day=26/hour=12/minute=21/second=29/format=csv/241202333553108863868724904588471509590.csv'
Data for row 1724 with id '100330567465073409813676396984498092882' uploaded to S3 bucket 'test-financial-news-bucket' under folder 'news/crypto/year=2026/month=02/day=26/hour=00/minute=40/second=15/format=csv/100330567465073409813676396984498092882.csv'
Data for row 1762 with id '237606200782224648434078595490849226748' uploaded to S3 bucket 'test-financial-news-bucket' under folder 'news/crypto/year=2026/month=02/day=26/hour=10/minute=58/second=17/format=csv/237606200782224648434078595490849226748.csv'
Data for row 1877 with id '194806727593937791218780398101332863539' uploaded to S3 bucket 'test-financial-news-bucket' under folder 'news/crypto/year=2026/month=02/day=26/hour=13/minute=16/second=14/format=csv/194806727593937791218780398101332863539.csv'
Data for row 1935 with id '836002712632387375913447106869464561' uploaded to S3 bucket 'test-financial-news-bucket' under folder 'news/crypto/year=2026/month=02/day=26/hour=17/minute=28/second=57/format=csv/836002712632387375913447106869464561.csv'
Data for row 2005 with id '277642282487726437296108874068244571054' uploaded to S3 bucket 'test-financial-news-bucket' under folder 'news/crypto/year=2026/month=02/day=26/hour=20/minute=37/second=48/format=csv/277642282487726437296108874068244571054.csv'
Data for row 2290 with id '69009750716751548593947293926176673672' uploaded to S3 bucket 'test-financial-news-bucket' under folder 'news/crypto/year=2026/month=02/day=26/hour=16/minute=19/second=41/format=csv/69009750716751548593947293926176673672.csv'
Data for row 2523 with id '116655132758201998813425585749784340633' uploaded to S3 bucket 'test-financial-news-bucket' under folder 'news/crypto/year=2026/month=02/day=26/hour=22/minute=28/second=34/format=csv/116655132758201998813425585749784340633.csv'
Data for row 2721 with id '272944559072452443423944060668365240289' uploaded to S3 bucket 'test-financial-news-bucket' under folder 'news/crypto/year=2026/month=02/day=26/hour=12/minute=32/second=15/format=csv/272944559072452443423944060668365240289.csv'
Data for row 2917 with id '145340874946946578912247973658905152996' uploaded to S3 bucket 'test-financial-news-bucket' under folder 'news/crypto/year=2026/month=02/day=26/hour=16/minute=15/second=32/format=csv/145340874946946578912247973658905152996.csv'
Data for row 3580 with id '16878896911238028252179429688580741413' uploaded to S3 bucket 'test-financial-news-bucket' under folder 'news/crypto/year=2026/month=02/day=26/hour=06/minute=40/second=46/format=csv/16878896911238028252179429688580741413.csv'
Data for row 3620 with id '150739403091458346768818952543146190404' uploaded to S3 bucket 'test-financial-news-bucket' under folder 'news/crypto/year=2026/month=02/day=26/hour=13/minute=44/second=10/format=csv/150739403091458346768818952543146190404.csv'
Data for row 4513 with id '269132289529055926602120223606146594366' uploaded to S3 bucket 'test-financial-news-bucket' under folder 'news/crypto/year=2026/month=02/day=26/hour=12/minute=10/second=24/format=csv/269132289529055926602120223606146594366.csv'
Data for row 4694 with id '335358695099567479689432336641344204447' uploaded to S3 bucket 'test-financial-news-bucket' under folder 'news/crypto/year=2026/month=02/day=26/hour=10/minute=02/second=26/format=csv/335358695099567479689432336641344204447.csv'
Data for row 5187 with id '324424735754841894083083377017176234849' uploaded to S3 bucket 'test-financial-news-bucket' under folder 'news/crypto/year=2026/month=02/day=26/hour=09/minute=57/second=00/format=csv/324424735754841894083083377017176234849.csv'
Data for row 5552 with id '254357223317187332356853124455594290289' uploaded to S3 bucket 'test-financial-news-bucket' under folder 'news/crypto/year=2026/month=02/day=26/hour=11/minute=45/second=48/format=csv/254357223317187332356853124455594290289.csv'
Data for row 5688 with id '299477662019204599522030187593056145176' uploaded to S3 bucket 'test-financial-news-bucket' under folder 'news/crypto/year=2026/month=02/day=26/hour=01/minute=57/second=24/format=csv/299477662019204599522030187593056145176.csv'
Data for row 5957 with id '317722175178271856349509314008579598017' uploaded to S3 bucket 'test-financial-news-bucket' under folder 'news/crypto/year=2026/month=02/day=26/hour=00/minute=01/second=07/format=csv/317722175178271856349509314008579598017.csv'
Data for row 6077 with id '312639301162012859860747087306797488360' uploaded to S3 bucket 'test-financial-news-bucket' under folder 'news/crypto/year=2026/month=02/day=26/hour=10/minute=19/second=00/format=csv/312639301162012859860747087306797488360.csv'
Data for row 6080 with id '180792496580054069091076487473421704685' uploaded to S3 bucket 'test-financial-news-bucket' under folder 'news/crypto/year=2026/month=02/day=26/hour=14/minute=01/second=02/format=csv/180792496580054069091076487473421704685.csv'
Data for row 6269 with id '57352908675248974179698197177761129110' uploaded to S3 bucket 'test-financial-news-bucket' under folder 'news/crypto/year=2026/month=02/day=26/hour=19/minute=13/second=45/format=csv/57352908675248974179698197177761129110.csv'
Data for row 6341 with id '274040477368068854164680307890552763944' uploaded to S3 bucket 'test-financial-news-bucket' under folder 'news/crypto/year=2026/month=02/day=26/hour=21/minute=12/second=52/format=csv/274040477368068854164680307890552763944.csv'
Data for row 6361 with id '231641270008039396331385234979857366859' uploaded to S3 bucket 'test-financial-news-bucket' under folder 'news/crypto/year=2026/month=02/day=26/hour=13/minute=24/second=21/format=csv/231641270008039396331385234979857366859.csv'
Data for row 6517 with id '38774894878942910786635264250221512924' uploaded to S3 bucket 'test-financial-news-bucket' under folder 'news/crypto/year=2026/month=02/day=26/hour=07/minute=53/second=22/format=csv/38774894878942910786635264250221512924.csv'
Data for row 6552 with id '220746314318332303343317269173587319856' uploaded to S3 bucket 'test-financial-news-bucket' under folder 'news/crypto/year=2026/month=02/day=26/hour=22/minute=30/second=13/format=csv/220746314318332303343317269173587319856.csv'

Data for row 6779 with id '86692656526731852253995490097593378898' uploaded to S3 bucket 'test-financial-news-bucket' under folder 'news/crypto/year=2026/month=02/day=26/hour=15/minute=03/second=12/format=csv/86692656526731852253995490097593378898.csv'
Data for row 7555 with id '98385637262610656159433038049773707344' uploaded to S3 bucket 'test-financial-news-bucket' under folder 'news/crypto/year=2026/month=02/day=26/hour=15/minute=45/second=39/format=csv/98385637262610656159433038049773707344.csv'
Data for row 8121 with id '250152591070998114758262892532058528046' uploaded to S3 bucket 'test-financial-news-bucket' under folder 'news/crypto/year=2026/month=02/day=26/hour=09/minute=36/second=14/format=csv/250152591070998114758262892532058528046.csv'
Data for row 8298 with id '179095415923007089299555914531049064910' uploaded to S3 bucket 'test-financial-news-bucket' under folder 'news/crypto/year=2026/month=02/day=26/hour=22/minute=00/second=03/format=csv/179095415923007089299555914531049064910.csv'
Data for row 8352 with id '56762510135637742695845811892114516204' uploaded to S3 bucket 'test-financial-news-bucket' under folder 'news/crypto/year=2026/month=02/day=26/hour=21/minute=04/second=47/format=csv/56762510135637742695845811892114516204.csv'
Data for row 8388 with id '73990382506785074632082127255550811462' uploaded to S3 bucket 'test-financial-news-bucket' under folder 'news/crypto/year=2026/month=02/day=26/hour=17/minute=24/second=25/format=csv/73990382506785074632082127255550811462.csv'
Data for row 8414 with id '94121152062151690186698825182488199943' uploaded to S3 bucket 'test-financial-news-bucket' under folder 'news/crypto/year=2026/month=02/day=26/hour=15/minute=55/second=53/format=csv/94121152062151690186698825182488199943.csv'
Data for row 8532 with id '178952551713809445216372092980526732708' uploaded to S3 bucket 'test-financial-news-bucket' under folder 'news/crypto/year=2026/month=02/day=26/hour=19/minute=08/second=11/format=csv/178952551713809445216372092980526732708.csv'
Data for row 8611 with id '176902851888858210026094555498753978941' uploaded to S3 bucket 'test-financial-news-bucket' under folder 'news/crypto/year=2026/month=02/day=26/hour=12/minute=21/second=44/format=csv/176902851888858210026094555498753978941.csv'
Data for row 8759 with id '76927369074518815711089262575509545373' uploaded to S3 bucket 'test-financial-news-bucket' under folder 'news/crypto/year=2026/month=02/day=26/hour=15/minute=16/second=11/format=csv/76927369074518815711089262575509545373.csv'
Data for row 9166 with id '296154784649561520591261926280690394611' uploaded to S3 bucket 'test-financial-news-bucket' under folder 'news/crypto/year=2026/month=02/day=26/hour=14/minute=04/second=07/format=csv/296154784649561520591261926280690394611.csv'
Data for row 9176 with id '307634511310167058765020796694458129095' uploaded to S3 bucket 'test-financial-news-bucket' under folder 'news/crypto/year=2026/month=02/day=26/hour=17/minute=00/second=00/format=csv/307634511310167058765020796694458129095.csv'
Data for row 9344 with id '48063747458451905470657862727640593833' uploaded to S3 bucket 'test-financial-news-bucket' under folder 'news/crypto/year=2026/month=02/day=26/hour=07/minute=47/second=51/format=csv/48063747458451905470657862727640593833.csv'
Data for row 9578 with id '61420049381796056555968395133231013582' uploaded to S3 bucket 'test-financial-news-bucket' under folder 'news/crypto/year=2026/month=02/day=26/hour=22/minute=00/second=00/format=csv/61420049381796056555968395133231013582.csv'
Data for row 9698 with id '109284113613115209922606764411305192677' uploaded to S3 bucket 'test-financial-news-bucket' under folder 'news/crypto/year=2026/month=02/day=26/hour=10/minute=03/second=33/format=csv/109284113613115209922606764411305192677.csv'
Data for row 9794 with id '36762157418640964393901353480119924276' uploaded to S3 bucket 'test-financial-news-bucket' under folder 'news/crypto/year=2026/month=02/day=26/hour=19/minute=25/second=45/format=csv/36762157418640964393901353480119924276.csv'
Data for row 9892 with id '314360726558574250865324575691679394939' uploaded to S3 bucket 'test-financial-news-bucket' under folder 'news/crypto/year=2026/month=02/day=26/hour=17/minute=57/second=01/format=csv/314360726558574250865324575691679394939.csv'
Task finished: all files were succesfully uploaded to S3 bucket test-financial-news-bucket

In [10]:
post_full_csv = False
if (post_full_csv == True) and not filtered_df.empty:
    now = datetime.now()
    filename = f"{now.year}-{now.month:02}-{now.day:02}_full_record"
    etl_export.set_dataframe(etl.df)
    etl_export.export_text_to_s3_full_file(bucket_name, prefix_path, filename)

In [11]:
ingest_data = False
get_full_file = True
get_by_datetime = False
df_from_file = None

if ingest_data == True:
    etl_ingestion = etl.Ingestion(etl.df)
    bucket_name = "test-financial-news-bucket"
    prefix_path = "news/crypto/"
    year = '2024'
    month = '08'
    day = '01'
    hour = ''
    minute = ''
    if get_full_file == True:
        filename = f"{year}-{month}-{day}_full_record.csv"
        full_path = f"{prefix_path}{filename}"
        df_from_file = etl_ingestion.get_full_data_csv_file(bucket_name, full_path)
    elif get_by_datetime == True:
        df_from_file = etl_ingestion.get_data_csv_file_by_datetime(bucket_name, prefix_path, year, month, day, hour, minute)

In [12]:
if df_from_file is not None:
    print(df_from_file.count())

In [13]:
# Assuming df is your DataFrame
targetId = ''
if len(targetId) > 0:
    filtered_content = filtered_df.loc[filtered_df['id'] == targetId, 'content']

    # If you want to display the full content, convert it to a list or display all rows
    full_content = filtered_content.tolist()

    print(full_content)