In [1]:
import sys
sys.path.append('../Storage')

import pgConn
import PostgresSQL_table_queries
import CloudStorage

import pandas as pd
from datetime import datetime

In [2]:
table_name = PostgresSQL_table_queries.FINANCIAL_NEWS_TABLE_NAME
pg_conn = pgConn.PgConn(table_name)
df = pg_conn.get_financial_news()

Connection to the database successful!
Table name set to: financial_news_241118

In [3]:
print(f"Total news articles queried: {df.shape[0]}")

Total news articles queried: 8419

In [4]:
df.head()

,id,source,headline,href,summary,content,author,minsread,datetime
0,45876047236640910017045281208231353781,Motley Fool,"""Tokenized"" Stocks Are Breaking Down Barriers....",https://finance.yahoo.com/news/tokenized-stock...,,In This Article:\nHOOD\n+0.23%\nAAPL\n-0.12%\n...,"Alex Carchidi, The Motley Fool",6 min read,2025-07-23T17:19:00.000Z
1,220799662638683730910896676542146227596,CoinDesk,"""We're a Tweet Away from a 15% Dump:"" CEO on C...",https://finance.yahoo.com/video/were-tweet-awa...,,"In today's Markets Outlook, CoinDesk's Jennife...",CoinDesk,,2025-10-31T17:34:16.000Z
2,47514014236007877639078711690178672970,Motley Fool,$1 Billion in New Capital Could Soon Flow to X...,https://finance.yahoo.com/news/1-billion-capit...,,In this article:\nXRP-USD\n-0.06%\nKey Points\...,"Alex Carchidi, The Motley Fool",5 min read,2025-11-02T11:35:00.000Z
3,152599983586513563130066357372522406611,Coinspeaker,"$1.2B Left BTC ETFs This Week, but Not All is ...",https://finance.yahoo.com/news/1-2b-left-btc-e...,,In this article:\nBTC-USD\n+0.22%\nSOSO-USD\n+...,Parth Dubey,2 min read,2025-10-18T10:15:49.000Z
4,214287918542718613358470608080600126044,TheStreet,$1.5M Bitcoin prediction firm Ark Invest calls...,https://finance.yahoo.com/news/1-5m-bitcoin-pr...,According to ARK Invest's latest Bitcoin month...,"The Cathie Wood-owned firm believes Bitcoin, w...",Anushka Basu,2 min read,2025-03-12T16:42:53.000Z

In [5]:
def delete_records_for_current_date(df, pg_conn):
    if df is None:
        print("DataFrame is empty. No records to delete.")
        return
        
    # Filter DataFrame for records with today's date
    current_date = datetime.now().strftime("%Y-%m-%d")
    today_records = df[df['datetime'].str.startswith(current_date)]

    # Extract date strings
    date_strings = today_records['datetime'].tolist()

    # Call the delete_records_by_date method
    pg_conn.delete_records_by_date(date_strings)

# Then call the delete_records_for_current_date method
#delete_records_for_current_date(df, pg_conn)
#list_ids = ["11111"]
#pg_conn.delete_records_by_ids(list_ids)

In [6]:
class DataETL():
    
    def __init__(self, dataframe):
            self.df = dataframe
            self.cloudProvider = CloudStorage.CloudStorageProvider()
            
    class Export():
        def __init__(self, dataframe):
            self.df = dataframe
            self.cloudProvider = CloudStorage.CloudStorageProvider()
            
        def set_dataframe(self, dataframe):
            self.df = dataframe
        
        def export_text_to_s3(self, bucket_name, prefix_path, file_format):
            # Initialize AWS storage
            aws_storage = self.cloudProvider.AWS()

            # Create a new bucket
            aws_storage.create_bucket(bucket_name)

            # Upload DataFrame with datetime subfolder structure
            aws_storage.upload_dataframe_with_datetime_subfolders(self.df, bucket_name, prefix_path, file_format)
        
        def export_text_to_s3_full_file(self, bucket_name, prefix_path, filename):
            aws_storage = self.cloudProvider.AWS()
            aws_storage.upload_dataframe_to_csv(self.df, bucket_name, filename, prefix_path)
            
    class Ingestion():
        def __init__(self, dataframe):
            self.df = dataframe
            self.cloudProvider = CloudStorage.CloudStorageProvider()
            
        def get_full_data_csv_file(self, bucket_name, prefix_path):
            # Initialize AWS storage
            aws_storage = self.cloudProvider.AWS()
            return aws_storage.get_csv_from_specific_folder(bucket_name, prefix_path)
        
        def get_data_csv_file_by_datetime(self, bucket_name, prefix_path, year, month, day, hour, minute):
            # Initialize AWS storage
            aws_storage = self.cloudProvider.AWS()
            return aws_storage.get_dataframe_from_specific_datetime(bucket_name, prefix_path, year=None, month=None, day=None, hour=None, minute=None)
    
    class Process():
        
        def __init__(self, dataframe):
            self.df = dataframe
        
        def getData():
            self.df = pg_conn.get_financial_news()
        
        def filter_by_current_date(self):
            # Get the current date as a string
            today_date_str = datetime.today().strftime('%Y-%m-%d')

            # Extract the year, month, and day from the current date string
            current_year, current_month, current_day = today_date_str.split('-')

            # Filter the DataFrame by comparing the substrings of the datetime column
            #filtered_df = self.df[self.df['datetime'].str.startswith(f'2025-06-05')]
            filtered_df = self.df[self.df['datetime'].str.startswith(f'{current_year}-{current_month}-{current_day}')]

            return filtered_df
            
    class Transform():
        def extractStopWords():
            pass

In [7]:
etl = DataETL(df)
etl_process = etl.Process(etl.df)
filtered_df = etl_process.filter_by_current_date()
filtered_df.head()

,id,source,headline,href,summary,content,author,minsread,datetime
173,217272938778449409016123602380133611564,99bitcoins,21Shares Unleashes 2x Dogecoin ETF as FalconX ...,https://finance.yahoo.com/news/21shares-unleas...,,In this article:\nDOGE-USD\n-6.68%\n21Shares h...,Anthony Clarke,3 min read,2025-11-21T02:27:09.000Z
184,165424556770101014893868590355257833027,BeInCrypto,3 Altcoins To Watch This Weekend | November 22...,https://finance.yahoo.com/news/3-altcoins-watc...,,In this article:\nSTRK22691-USD\n-10.24%\nBTC-...,Aaryamann Shrivastava,3 min read,2025-11-21T17:00:00.000Z
673,132322747733831210226666997471276584591,Investopedia,Are Stocks Weighing on Crypto—Or the Other Way...,https://finance.yahoo.com/news/stocks-weighing...,,In this article:\nBTC-USD\n-1.34%\n^SPX\n+0.98...,Crystal Kim,3 min read,2025-11-21T17:29:10.000Z
689,96140925535498062436250156282789988592,Coinspeaker,Arkham Exchange Partners with MoonPay to Simpl...,https://finance.yahoo.com/news/arkham-exchange...,,Arkham Exchange has partnered with MoonPay to ...,Tristan Greene,2 min read,2025-11-21T18:13:32.000Z
837,16115145180345613357036732113900079684,Stacker,BNPL usage rises alongside late payments and r...,https://finance.yahoo.com/news/bnpl-usage-rise...,,In this article:\nKLAR\n+3.42%\nA person holdi...,Jack Caporal for Motley Fool Money,10 min read,2025-11-21T16:30:08.000Z

In [8]:
print(f"Total filtered news articles queried: {filtered_df.shape[0]}")

Total filtered news articles queried: 57

In [9]:
export_rows_to_s3 = True
etl_export = etl.Export(filtered_df)
bucket_name = "test-financial-news-bucket"
prefix_path = "news/crypto"
file_format = "csv"
if export_rows_to_s3 == True and not filtered_df.empty:
    etl_export.export_text_to_s3(bucket_name, prefix_path, file_format)

Bucket 'test-financial-news-bucket' created successfully.
Data for row 173 with id '217272938778449409016123602380133611564' uploaded to S3 bucket 'test-financial-news-bucket' under folder 'news/crypto/year=2025/month=11/day=21/hour=02/minute=27/second=09/format=csv/217272938778449409016123602380133611564.csv'
Data for row 184 with id '165424556770101014893868590355257833027' uploaded to S3 bucket 'test-financial-news-bucket' under folder 'news/crypto/year=2025/month=11/day=21/hour=17/minute=00/second=00/format=csv/165424556770101014893868590355257833027.csv'
Data for row 673 with id '132322747733831210226666997471276584591' uploaded to S3 bucket 'test-financial-news-bucket' under folder 'news/crypto/year=2025/month=11/day=21/hour=17/minute=29/second=10/format=csv/132322747733831210226666997471276584591.csv'
Data for row 689 with id '96140925535498062436250156282789988592' uploaded to S3 bucket 'test-financial-news-bucket' under folder 'news/crypto/year=2025/month=11/day=21/hour=18/minute=13/second=32/format=csv/96140925535498062436250156282789988592.csv'
Data for row 837 with id '16115145180345613357036732113900079684' uploaded to S3 bucket 'test-financial-news-bucket' under folder 'news/crypto/year=2025/month=11/day=21/hour=16/minute=30/second=08/format=csv/16115145180345613357036732113900079684.csv'
Data for row 902 with id '141407131569376332919880616519299146693' uploaded to S3 bucket 'test-financial-news-bucket' under folder 'news/crypto/year=2025/month=11/day=21/hour=18/minute=53/second=37/format=csv/141407131569376332919880616519299146693.csv'
Data for row 951 with id '198522385640090309388708460273645930701' uploaded to S3 bucket 'test-financial-news-bucket' under folder 'news/crypto/year=2025/month=11/day=21/hour=18/minute=06/second=31/format=csv/198522385640090309388708460273645930701.csv'
Data for row 979 with id '118724585529367196665921792520619131496' uploaded to S3 bucket 'test-financial-news-bucket' under folder 'news/crypto/year=2025/month=11/day=21/hour=01/minute=01/second=20/format=csv/118724585529367196665921792520619131496.csv'
Data for row 1003 with id '231393868845294056306853151178660749756' uploaded to S3 bucket 'test-financial-news-bucket' under folder 'news/crypto/year=2025/month=11/day=21/hour=17/minute=24/second=06/format=csv/231393868845294056306853151178660749756.csv'
Data for row 1052 with id '240187500164519014604187753243359366117' uploaded to S3 bucket 'test-financial-news-bucket' under folder 'news/crypto/year=2025/month=11/day=21/hour=18/minute=06/second=51/format=csv/240187500164519014604187753243359366117.csv'
Data for row 1061 with id '226631970180070561768593073654463116928' uploaded to S3 bucket 'test-financial-news-bucket' under folder 'news/crypto/year=2025/month=11/day=21/hour=16/minute=41/second=16/format=csv/226631970180070561768593073654463116928.csv'
Data for row 1216 with id '309366203013203861960394364220491341428' uploaded to S3 bucket 'test-financial-news-bucket' under folder 'news/crypto/year=2025/month=11/day=21/hour=00/minute=36/second=41/format=csv/309366203013203861960394364220491341428.csv'
Data for row 1226 with id '62297470615615751342042155938903934604' uploaded to S3 bucket 'test-financial-news-bucket' under folder 'news/crypto/year=2025/month=11/day=21/hour=18/minute=19/second=52/format=csv/62297470615615751342042155938903934604.csv'
Data for row 1361 with id '294992934044424887626366784943074267165' uploaded to S3 bucket 'test-financial-news-bucket' under folder 'news/crypto/year=2025/month=11/day=21/hour=16/minute=48/second=52/format=csv/294992934044424887626366784943074267165.csv'
Data for row 1366 with id '224754172744991731895018338939879382920' uploaded to S3 bucket 'test-financial-news-bucket' under folder 'news/crypto/year=2025/month=11/day=21/hour=16/minute=51/second=55/format=csv/224754172744991731895018338939879382920.csv'
Data for row 1546 with id '89672899804963849181798171686541812748' uploaded to S3 bucket 'test-financial-news-bucket' under folder 'news/crypto/year=2025/month=11/day=21/hour=18/minute=49/second=27/format=csv/89672899804963849181798171686541812748.csv'
Data for row 1711 with id '324100820174996509147631127793913172109' uploaded to S3 bucket 'test-financial-news-bucket' under folder 'news/crypto/year=2025/month=11/day=21/hour=23/minute=11/second=13/format=csv/324100820174996509147631127793913172109.csv'
Data for row 2012 with id '183750006603964540461799499808290262187' uploaded to S3 bucket 'test-financial-news-bucket' under folder 'news/crypto/year=2025/month=11/day=21/hour=16/minute=31/second=02/format=csv/183750006603964540461799499808290262187.csv'
Data for row 2217 with id '1140573250698351435117534600466070650' uploaded to S3 bucket 'test-financial-news-bucket' under folder 'news/crypto/year=2025/month=11/day=21/hour=18/minute=18/second=06/format=csv/1140573250698351435117534600466070650.csv'
Data for row 2231 with id '120551827471878394970583129820724791718' uploaded to S3 bucket 'test-financial-news-bucket' under folder 'news/crypto/year=2025/month=11/day=21/hour=17/minute=25/second=07/format=csv/120551827471878394970583129820724791718.csv'
Data for row 2431 with id '3916420823700842225808870008842356746' uploaded to S3 bucket 'test-financial-news-bucket' under folder 'news/crypto/year=2025/month=11/day=21/hour=16/minute=23/second=59/format=csv/3916420823700842225808870008842356746.csv'
Data for row 2432 with id '72597656869853954528195434057147465300' uploaded to S3 bucket 'test-financial-news-bucket' under folder 'news/crypto/year=2025/month=11/day=21/hour=18/minute=01/second=29/format=csv/72597656869853954528195434057147465300.csv'
Data for row 2483 with id '293617950363495049506052506748706602300' uploaded to S3 bucket 'test-financial-news-bucket' under folder 'news/crypto/year=2025/month=11/day=21/hour=02/minute=25/second=44/format=csv/293617950363495049506052506748706602300.csv'
Data for row 2891 with id '113109191155699840506736593567159047035' uploaded to S3 bucket 'test-financial-news-bucket' under folder 'news/crypto/year=2025/month=11/day=21/hour=17/minute=51/second=25/format=csv/113109191155699840506736593567159047035.csv'
Data for row 3148 with id '204123341563024225576763780350513289267' uploaded to S3 bucket 'test-financial-news-bucket' under folder 'news/crypto/year=2025/month=11/day=21/hour=01/minute=17/second=39/format=csv/204123341563024225576763780350513289267.csv'
Data for row 3704 with id '326718579961483490211598100164250770705' uploaded to S3 bucket 'test-financial-news-bucket' under folder 'news/crypto/year=2025/month=11/day=21/hour=11/minute=02/second=18/format=csv/326718579961483490211598100164250770705.csv'
Data for row 3780 with id '285949430305285418774934239192259829635' uploaded to S3 bucket 'test-financial-news-bucket' under folder 'news/crypto/year=2025/month=11/day=21/hour=17/minute=27/second=38/format=csv/285949430305285418774934239192259829635.csv'
Data for row 3894 with id '260924659070534067081791670886951840131' uploaded to S3 bucket 'test-financial-news-bucket' under folder 'news/crypto/year=2025/month=11/day=21/hour=16/minute=52/second=06/format=csv/260924659070534067081791670886951840131.csv'
Data for row 4059 with id '147272866474438521462633950163853071751' uploaded to S3 bucket 'test-financial-news-bucket' under folder 'news/crypto/year=2025/month=11/day=21/hour=18/minute=43/second=36/format=csv/147272866474438521462633950163853071751.csv'
Data for row 4070 with id '74259265262289377892260647850481566966' uploaded to S3 bucket 'test-financial-news-bucket' under folder 'news/crypto/year=2025/month=11/day=21/hour=16/minute=46/second=34/format=csv/74259265262289377892260647850481566966.csv'
Data for row 4170 with id '89350119993506596955253918611360130589' uploaded to S3 bucket 'test-financial-news-bucket' under folder 'news/crypto/year=2025/month=11/day=21/hour=00/minute=44/second=10/format=csv/89350119993506596955253918611360130589.csv'
Data for row 4172 with id '287874099770968671253714104804059847092' uploaded to S3 bucket 'test-financial-news-bucket' under folder 'news/crypto/year=2025/month=11/day=21/hour=20/minute=07/second=52/format=csv/287874099770968671253714104804059847092.csv'
Data for row 4268 with id '40494542807119973142671162019612252292' uploaded to S3 bucket 'test-financial-news-bucket' under folder 'news/crypto/year=2025/month=11/day=21/hour=18/minute=21/second=40/format=csv/40494542807119973142671162019612252292.csv'

Data for row 4323 with id '62149667337311569883156090235725984995' uploaded to S3 bucket 'test-financial-news-bucket' under folder 'news/crypto/year=2025/month=11/day=21/hour=16/minute=34/second=01/format=csv/62149667337311569883156090235725984995.csv'
Data for row 4675 with id '105715321083202295986155242396414512117' uploaded to S3 bucket 'test-financial-news-bucket' under folder 'news/crypto/year=2025/month=11/day=21/hour=18/minute=30/second=00/format=csv/105715321083202295986155242396414512117.csv'
Data for row 4855 with id '139563263926052852871486232797920085481' uploaded to S3 bucket 'test-financial-news-bucket' under folder 'news/crypto/year=2025/month=11/day=21/hour=00/minute=39/second=00/format=csv/139563263926052852871486232797920085481.csv'
Data for row 4910 with id '325604995667884066587739340895504689131' uploaded to S3 bucket 'test-financial-news-bucket' under folder 'news/crypto/year=2025/month=11/day=21/hour=20/minute=05/second=31/format=csv/325604995667884066587739340895504689131.csv'
Data for row 5232 with id '209639522493550416993878311039506834283' uploaded to S3 bucket 'test-financial-news-bucket' under folder 'news/crypto/year=2025/month=11/day=21/hour=22/minute=53/second=07/format=csv/209639522493550416993878311039506834283.csv'
Data for row 5363 with id '163526523618552361745522151077635053412' uploaded to S3 bucket 'test-financial-news-bucket' under folder 'news/crypto/year=2025/month=11/day=21/hour=19/minute=08/second=29/format=csv/163526523618552361745522151077635053412.csv'
Data for row 5632 with id '153985365466350053011618238412424144212' uploaded to S3 bucket 'test-financial-news-bucket' under folder 'news/crypto/year=2025/month=11/day=21/hour=21/minute=55/second=37/format=csv/153985365466350053011618238412424144212.csv'
Data for row 5791 with id '37113665936653274884134084145127513264' uploaded to S3 bucket 'test-financial-news-bucket' under folder 'news/crypto/year=2025/month=11/day=21/hour=00/minute=00/second=00/format=csv/37113665936653274884134084145127513264.csv'
Data for row 6125 with id '105238606023616992164417777169770575368' uploaded to S3 bucket 'test-financial-news-bucket' under folder 'news/crypto/year=2025/month=11/day=21/hour=01/minute=02/second=36/format=csv/105238606023616992164417777169770575368.csv'
Data for row 6349 with id '336123381734691485256559784160287826599' uploaded to S3 bucket 'test-financial-news-bucket' under folder 'news/crypto/year=2025/month=11/day=21/hour=23/minute=04/second=36/format=csv/336123381734691485256559784160287826599.csv'
Data for row 6537 with id '152577396326715138386929489609493444833' uploaded to S3 bucket 'test-financial-news-bucket' under folder 'news/crypto/year=2025/month=11/day=21/hour=17/minute=31/second=16/format=csv/152577396326715138386929489609493444833.csv'
Data for row 7627 with id '145317338413294166131029411304976592645' uploaded to S3 bucket 'test-financial-news-bucket' under folder 'news/crypto/year=2025/month=11/day=21/hour=19/minute=00/second=00/format=csv/145317338413294166131029411304976592645.csv'
Data for row 7679 with id '332580709962006372478034676772020485945' uploaded to S3 bucket 'test-financial-news-bucket' under folder 'news/crypto/year=2025/month=11/day=21/hour=18/minute=08/second=31/format=csv/332580709962006372478034676772020485945.csv'
Data for row 7695 with id '251118986679279820090115181666370951689' uploaded to S3 bucket 'test-financial-news-bucket' under folder 'news/crypto/year=2025/month=11/day=21/hour=18/minute=43/second=00/format=csv/251118986679279820090115181666370951689.csv'
Data for row 7768 with id '148905873833860145242640706291550171314' uploaded to S3 bucket 'test-financial-news-bucket' under folder 'news/crypto/year=2025/month=11/day=21/hour=17/minute=44/second=13/format=csv/148905873833860145242640706291550171314.csv'
Data for row 7795 with id '115647931825529489906555331353628455418' uploaded to S3 bucket 'test-financial-news-bucket' under folder 'news/crypto/year=2025/month=11/day=21/hour=00/minute=31/second=37/format=csv/115647931825529489906555331353628455418.csv'
Data for row 7810 with id '317564357913655233962752926960066115807' uploaded to S3 bucket 'test-financial-news-bucket' under folder 'news/crypto/year=2025/month=11/day=21/hour=22/minute=07/second=33/format=csv/317564357913655233962752926960066115807.csv'
Data for row 7843 with id '48245144795681420028080673736582455910' uploaded to S3 bucket 'test-financial-news-bucket' under folder 'news/crypto/year=2025/month=11/day=21/hour=00/minute=19/second=25/format=csv/48245144795681420028080673736582455910.csv'
Data for row 7881 with id '223772145110958075825808060625478083353' uploaded to S3 bucket 'test-financial-news-bucket' under folder 'news/crypto/year=2025/month=11/day=21/hour=22/minute=50/second=30/format=csv/223772145110958075825808060625478083353.csv'
Data for row 7944 with id '100533797269096651346997213670424755566' uploaded to S3 bucket 'test-financial-news-bucket' under folder 'news/crypto/year=2025/month=11/day=21/hour=18/minute=51/second=19/format=csv/100533797269096651346997213670424755566.csv'
Data for row 8032 with id '88357165632906958887554919674776348854' uploaded to S3 bucket 'test-financial-news-bucket' under folder 'news/crypto/year=2025/month=11/day=21/hour=18/minute=53/second=58/format=csv/88357165632906958887554919674776348854.csv'
Data for row 8343 with id '194073386258640102336234716171865140529' uploaded to S3 bucket 'test-financial-news-bucket' under folder 'news/crypto/year=2025/month=11/day=21/hour=00/minute=00/second=00/format=csv/194073386258640102336234716171865140529.csv'
Data for row 8378 with id '250226088498106989647857045125273910144' uploaded to S3 bucket 'test-financial-news-bucket' under folder 'news/crypto/year=2025/month=11/day=21/hour=22/minute=20/second=59/format=csv/250226088498106989647857045125273910144.csv'
Data for row 8416 with id '14146428049608211291140685856506331366' uploaded to S3 bucket 'test-financial-news-bucket' under folder 'news/crypto/year=2025/month=11/day=21/hour=16/minute=56/second=28/format=csv/14146428049608211291140685856506331366.csv'
Task finished: all files were succesfully uploaded to S3 bucket test-financial-news-bucket

In [10]:
post_full_csv = False
if (post_full_csv == True) and not filtered_df.empty:
    now = datetime.now()
    filename = f"{now.year}-{now.month:02}-{now.day:02}_full_record"
    etl_export.set_dataframe(etl.df)
    etl_export.export_text_to_s3_full_file(bucket_name, prefix_path, filename)

In [11]:
ingest_data = False
get_full_file = True
get_by_datetime = False
df_from_file = None

if ingest_data == True:
    etl_ingestion = etl.Ingestion(etl.df)
    bucket_name = "test-financial-news-bucket"
    prefix_path = "news/crypto/"
    year = '2024'
    month = '08'
    day = '01'
    hour = ''
    minute = ''
    if get_full_file == True:
        filename = f"{year}-{month}-{day}_full_record.csv"
        full_path = f"{prefix_path}{filename}"
        df_from_file = etl_ingestion.get_full_data_csv_file(bucket_name, full_path)
    elif get_by_datetime == True:
        df_from_file = etl_ingestion.get_data_csv_file_by_datetime(bucket_name, prefix_path, year, month, day, hour, minute)

In [12]:
if df_from_file is not None:
    print(df_from_file.count())

In [13]:
# Assuming df is your DataFrame
targetId = ''
if len(targetId) > 0:
    filtered_content = filtered_df.loc[filtered_df['id'] == targetId, 'content']

    # If you want to display the full content, convert it to a list or display all rows
    full_content = filtered_content.tolist()

    print(full_content)